blank_issues_enabled: false
contact_links:
  - name: Support & Questions
    url: https://github.com/hazeezet/dynamodb-migrator/discussions
    about: Please use GitHub Discussions for general questions or community support.
